config/routes.rb
Rails.application.routes.draw do

  resources :zones
  resources :sectors
  resources :afiches
  get 'verificacionusers/index'

  resources :voluntario_pruebas
  resources :respuesta
  resources :resultados
  resources :opciones_respuesta
  resources :pregunta
  resources :pruebas_competencia
  resources :aptitudes
  resources :nivelacademicos
  resources :jornadaestudios
  resources :tipoestudios
  resources :ultimotitulos
  resources :tipocontactos
  resources :tenenciaviviendas
  resources :detalleubicacions
  resources :ubicacionviviendas
  resources :religions
  resources :tipo_estado_civils
  resources :tipo_de_sexos
  resources :tipo_documentos
  resources :paises
  resources :municipios
  resources :departamentos
  root 'home#index'







  resources :publicaciones


  get 'prueba/index'
  get 'home/conpruebas'
  get 'home/convocatorias'

  get '/conpruebas/:id', to: 'home#conpruebasid'
  get '/imprimir/:id', to: 'home#imprimir'


  get '/exvoluntarios', to: 'home#exvoluntarios'
  get '/exong', to: 'home#exong'
  get '/exingresos', to: 'home#exingresos'

  get '/exaprovol', to: 'home#exaprovol'
  get '/exaproong', to: 'home#exaproong'

  get '/exevaluacion', to: 'home#exevaluacion'

  get '/ong/new', to: 'verificacionusers#ong'




  get '/home/voluntario/:id', to: 'home#voluntario'
  get '/home/ong/:id', to: 'home#ong'


  post '/home/aprobacion', to: 'home#aprobacion'
  post '/home/bloquear', to: 'home#bloquear'
  post '/home/aplicarconvocatoria', to: 'home#aplicarconvocatoria'
  post '/ong/create', to: 'verificacionusers#ongcreate'
  post '/voluntario/create', to: 'verificacionusers#voluntariocreate'
  get '/v1/departamentos' , to: 'verificacionusers#departamentos'


  get '/newadmin' , to: 'verificacionusers#newadmin'
  post '/createadmin' , to: 'verificacionusers#createadmin'

  get '/editadmin/:id' , to: 'verificacionusers#editadmin'
  post '/updateadmin' , to: 'verificacionusers#updateadmin'

  delete '/admindestroy/:id' , to: 'verificacionusers#admindestroy'



  get '/v1/municipios/:id', to: 'verificacionusers#municipios'
  post '/pruebasresp', to: 'home#pruebasresp'
  put '/subirdocumentos', to: 'home#edit'


  post '/checkemail', to: 'verificacionusers#emailcheck'

  get 'prueba/show'



  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
end

app/models/afich.rb
class Afich < ApplicationRecord
  has_many :aficherequisitos
  has_many :aplicacionafiche
  belongs_to :user
end

app/models/aptitude.rb
class Aptitude < ApplicationRecord
  has_many :aficherequisitos
end

app/models/departamento.rb
class Departamento < ApplicationRecord
  has_many :municipios
end

app/models/detalleubicacion.rb
class Detalleubicacion < ApplicationRecord
  belongs_to :ubicacionvivienda
end

app/models/municipio.rb
class Municipio < ApplicationRecord
  belongs_to :departamento
end

app/models/ong.rb
class Ong < ApplicationRecord
  belongs_to :user

  has_attached_file :camaracomercio
  has_attached_file :documentoidentidad
  has_attached_file :rut

  do_not_validate_attachment_file_type :camaracomercio
  do_not_validate_attachment_file_type :documentoidentidad
  do_not_validate_attachment_file_type :rut
end

app/models/paise.rb
class Paise < ApplicationRecord
  has_many :users

end

app/models/pregunta.rb
class Pregunta < ApplicationRecord
  belongs_to :pruebas_competencia
  has_many :opciones_respuestums, :dependent => :delete_all
end

app/models/religion.rb
class Religion < ApplicationRecord
end

app/models/respuesta.rb
class Respuesta < ApplicationRecord
  belongs_to :resultado
end

app/models/resultado.rb
class Resultado < ApplicationRecord
  belongs_to :user
  has_many :respuestas
  belongs_to :pruebas_competencia
end

app/models/sector.rb
class Sector < ApplicationRecord
  belongs_to :municipio
end

app/models/tipo_de_sexo.rb
class TipoDeSexo < ApplicationRecord
  has_many :users
end

app/models/tipocontacto.rb
class Tipocontacto < ApplicationRecord
end

app/models/tipoestudio.rb
class Tipoestudio < ApplicationRecord
end

app/models/tipouser.rb
class Tipouser < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_one :tipo_documento
  has_one :municipio
  has_one :ong
  has_one :voluntario
  has_many :afiches
  has_many :aplicacionafiche
  has_many :resultados





  def self.search(email)
    if email
      where('email = ?',email).first
    end

  end











  #validates :nombres, :presence => true
  #validates :apellidos, :presence => true
  #validates :numdoc, :presence => true
  #validates :tipo_de_sexos_id, :presence => true
  #validates :paises_id, :presence => true
  #validates :tipo_estado_civils_id, :presence => true
  #validates :ubicacionviviendas_id, :presence => true
  #validates :tenenciaviviendas_id, :presence => true
  #validates :nivelacademicos_id, :presence => true







  has_attached_file :certestudios
  has_attached_file :certexperiencia
  has_attached_file :docidentidad
  has_attached_file :tarjetaprofesional

  has_attached_file :camaracomercio
  has_attached_file :rut


  do_not_validate_attachment_file_type :certestudios
  do_not_validate_attachment_file_type :docidentidad
  do_not_validate_attachment_file_type :tarjetaprofesional
  do_not_validate_attachment_file_type :camaracomercio
  do_not_validate_attachment_file_type :rut
  do_not_validate_attachment_file_type :certexperiencia

  # has_one :tipo_de_sexos


end

app/models/voluntario.rb
class Voluntario < ApplicationRecord
  belongs_to :user




  has_attached_file :certestudios
  has_attached_file :certexperiencia
  has_attached_file :docidentidad
  has_attached_file :tarjetaprofesional

  do_not_validate_attachment_file_type :certestudios
  do_not_validate_attachment_file_type :certexperiencia
  do_not_validate_attachment_file_type :docidentidad
  do_not_validate_attachment_file_type :tarjetaprofesional
end

app/models/zone.rb
class Zone < ApplicationRecord
  belongs_to :sector
end

app/controllers/detalleubicacions_controller.rb
class DetalleubicacionsController < ApplicationController
  before_action :set_detalleubicacion, only: [:show, :edit, :update, :destroy]

  # GET /detalleubicacions
  # GET /detalleubicacions.json
  def index
    @detalleubicacions = Detalleubicacion.all
  end

  # GET /detalleubicacions/1
  # GET /detalleubicacions/1.json
  def show
  end

  # GET /detalleubicacions/new
  def new
    @detalleubicacion = Detalleubicacion.new
  end

  # GET /detalleubicacions/1/edit
  def edit
  end

  # POST /detalleubicacions
  # POST /detalleubicacions.json
  def create
    @detalleubicacion = Detalleubicacion.new(detalleubicacion_params)

    respond_to do |format|
      if @detalleubicacion.save
        format.html { redirect_to @detalleubicacion, notice: 'Detalleubicacion was successfully created.' }
        format.json { render :show, status: :created, location: @detalleubicacion }
      else
        format.html { render :new }
        format.json { render json: @detalleubicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detalleubicacions/1
  # PATCH/PUT /detalleubicacions/1.json
  def update
    respond_to do |format|
      if @detalleubicacion.update(detalleubicacion_params)
        format.html { redirect_to @detalleubicacion, notice: 'Detalleubicacion was successfully updated.' }
        format.json { render :show, status: :ok, location: @detalleubicacion }
      else
        format.html { render :edit }
        format.json { render json: @detalleubicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detalleubicacions/1
  # DELETE /detalleubicacions/1.json
  def destroy
    @detalleubicacion.destroy
    respond_to do |format|
      format.html { redirect_to detalleubicacions_url, notice: 'Detalleubicacion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detalleubicacion
      @detalleubicacion = Detalleubicacion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detalleubicacion_params
      params.require(:detalleubicacion).permit(:nombre, :ubicacionvivienda_id)
    end
end

app/helpers/detalleubicacions_helper.rb
module DetalleubicacionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/detalleubicacions/_form.html.erb
<div class="ui container">
<%= form_for(detalleubicacion) do |f| %>
  <% if detalleubicacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detalleubicacion.errors.count, "error") %> prohibited this detalleubicacion from being saved:</h2>

      <ul>
      <% detalleubicacion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :ubicacionvivienda_id %>
    <%= f.text_field :ubicacionvivienda_id %>
  </div>

  <div class="actions">
    <%= f.submit "Crear",  class:"ui primary button btnLogin"  %>
  </div>
<% end %>
</div>

app/views/detalleubicacions/edit.html.erb
<div class="ui container">
<h1>Editar Detalle De Ubicacion</h1>

<%= render 'form', detalleubicacion: @detalleubicacion %>

<%= link_to 'Mirar', @detalleubicacion %> |
<%= link_to 'Regresar', detalleubicacions_path %>
</div>

app/views/detalleubicacions/index.html.erb
<div class="ui container">
<p id="notice"><%= notice %></p>

<h1>Detalle de Ubicacions</h1>

  <table class="ui unstackable table">
    <thead>
    <tr>

      <th>Nombre</th>
      <th>Mirar</th>
      <th>Editar</th>
      <th>Eliminar</th>

    </tr>
    </thead>

    <tbody>
    <% @detalleubicacions.each do |detalleubicacion| %>
        <tr>
          <td><%= detalleubicacion.nombre %></td>
          <td><%= link_to 'Mirar', detalleubicacion %></td>
          <td><%= link_to 'Editar', edit_detalleubicacion_path(detalleubicacion) %></td>
          <td><%= link_to 'Eliminar', detalleubicacion, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <br>

<%= link_to 'Nuevo Detalle de Ubicacion', new_detalleubicacion_path %>
</div>

app/views/detalleubicacions/new.html.erb
<div class="ui container">

<h1>Nuevo Detall De Ubicacion</h1>

<%= render 'form', detalleubicacion: @detalleubicacion %>

<%= link_to 'Regresar', detalleubicacions_path %>
</div>

app/views/detalleubicacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @detalleubicacion.nombre %>
</p>

<p>
  <strong>Ubicacionvivienda:</strong>
  <%= @detalleubicacion.ubicacionvivienda %>
</p>

<%= link_to 'Edit', edit_detalleubicacion_path(@detalleubicacion) %> |
<%= link_to 'Back', detalleubicacions_path %>